name: GitHub Actions Demo Teste

on:
  push: 
    branches: [main]
    paths-ignore: [.github/**]
    
  pull_request:
    branches: [main]
  
  
  schedule:
    - cron: '25 7 *  * 0'
  workflow_dispatch:
  
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    
    
  
  
  
  
    
